In [1]:
import numpy as np

In [3]:
from __future__ import division

In [4]:
5/2 

2.5

In [8]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [9]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [10]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [11]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [12]:
arr1 **3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

In [13]:
arr = np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr[0:5] = 100

In [16]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [20]:
arr = np.arange(0,11)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
slice = arr[0:6]

In [23]:
slice

array([0, 1, 2, 3, 4, 5])

In [24]:
slice[:] =99

In [25]:
slice

array([99, 99, 99, 99, 99, 99])

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [31]:
 arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[0]

array([ 5, 10, 15])

In [34]:
arr_2d[0,1]

10

In [35]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [39]:
arr_2d = np.zeros((10,10))

In [40]:
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [42]:
length = arr_2d.shape[1]

In [43]:
for i in range(length):
    arr_2d[i] = i

In [44]:
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [45]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [46]:
arr_2d[[2,4]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.]])