In [1]:
import numpy as np

In [4]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [8]:
A = np.random.randn(10)
A

array([-0.9718409 ,  0.80828746, -0.49014584,  0.82418838, -0.05304368,
        0.39649073,  1.14937835, -1.97987006,  0.71147563,  1.24142405])

In [9]:
B = np.random.randn(10)
B

array([-0.31124461,  0.72912454, -0.76873949,  0.49249435, -0.16061145,
        1.37141827, -2.6607389 ,  0.2643305 , -0.27862212,  0.21911318])

In [10]:
np.add(A,B)

array([-1.28308551,  1.537412  , -1.25888533,  1.31668273, -0.21365513,
        1.76790899, -1.51136055, -1.71553956,  0.43285351,  1.46053723])

In [12]:
np.maximum(A,B)

array([-0.31124461,  0.80828746, -0.49014584,  0.82418838, -0.05304368,
        1.37141827,  1.14937835,  0.2643305 ,  0.71147563,  1.24142405])